export const ADD_EXAMPLE_SUCCESS = 'ADD_EXAMPLE_SUCCESS';
export const ADD_EXAMPLE_PENDING = 'ADD_EXAMPLE_PENDING';
export const ADD_EXAMPLE_FAILED = 'ADD_EXAMPLE_FAILED';

export const GET_EXAMPLE_SUCCESS = 'GET_EXAMPLE_SUCCESS';
export const GET_EXAMPLE_PENDING = 'GET_EXAMPLE_PENDING';
export const GET_EXAMPLE_FAILED = 'GET_EXAMPLE_FAILED';
